spring:
  application:
    name: data-ingestion-service

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

coincap:
  base-url: https://api.coincap.io/v2
  api-key: ${COINCAP_API_KEY}

bucket:
  rate-limit: 500
  time-period: 60

api:
  scheduled:
    interval: 6000


