spring:
  application:
    name: data-ingestion-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

kafka:
  topic:
    status
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: org.apache.kafka.common.serialization.JsonDeserializer
    properties:
      retries: 3
      delivery.timeout.ms: 120000
      request.timeout.ms: 60000
      spring.json.trusted.packages: "*"
      enable.idempotence: true

resilience4j.circuitbreaker:
  instances:
    pipeline:
      register-health-indicator: true
      sliding-window-type: TIME_BASED
      sliding-window-size: 300
      minimum-number-of-calls: 1
      failure-rate-threshold: 50
      wait-duration-in-open-state: 300s # 5 minutes
      permitted-number-of-calls-in-half-open-state: 1

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers

logging:
  level:
    root: INFO





