spring:
  application:
    name: data-ingestion-service

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

coincap:
  websocket:
    url:
      asset: "wss://ws.coincap.io/prices?assets=ALL"
  rest-api:
    base_url: api.coincap.io/v2

limits:
    max-requests: 200
    max-retries: 3
    refresh-rate: 1

raw-data:
  market: "raw_market"
  candle: "raw_candle"

resilience4j:
  retry:
    instances:
      fetchDataRetry:
        maxRetryAttempts: 6
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.ResponseStatusException
  circuitbreaker:
    instances:
      fetchDataBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10

    management:
      endpoints:
        web:
          exposure:
            include: '*'


