spring:
  application:
    name: data-ingestion-service

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

coincap:
  websocket:
    url:
      asset: "wss://ws.coincap.io/prices?assets=ALL"
  rest-api:
    base_url: api.coincap.io/v2

limits:
    max-requests: 200
    max-retries: 3
    refresh-rate: 1

raw-data:
  market: "raw_market"