spring:
  application:
    name: data-ingestion-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration


kafka:
  topic:
    status
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: org.apache.kafka.common.serialization.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

resilience4j.circuitbreaker:
  instances:
    apiCircuitBreaker:
      registerHealthIndicator: true
      sliding-window-size: 10
      failure-rate-threshold: 3
      wait-duration-in-open-state: 10s

logging:
  level:
    root: INFO




