spring:
  application:
    name: data-ingestion-service

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

coincap:
  websocket:
    url:
      asset: "wss://ws.coincap.io/prices?assets=ALL"

  rest-api:
    base_url: api.coincap.io/v2

limits:
    max-requests: 200
    max-retries: 3
    refresh-rate: 1

raw-data:
  market: "raw_market"
  candle: "raw_candle"

resilience4j:
  retry:
    instances:
      manageFetch:
        maxRetryAttempts: 6
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.ResponseStatusException
          - java.io.IOException

  circuitbreaker:
    instances:
      manageFetch:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

    management:
      endpoints:
        web:
          exposure:
            include: '*'

      endpoint:
        health:
          show-details: always


