spring:
  application:
    name: data-ingestion-service
  profile:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

coincap:
  base-url: https://api.coincap.io/v2
  api-key: ${CC_API_KEY}

resilience4j.circuitbreaker:
  instances:
    apiCircuitBreaker:
      registerHealthIndicator: true
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s

resilience4j.retry:
  instances:
    apiRetry:
      max-attempts: 3
      wait-duration: 100ms
      enableExponentialBackoff: true
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException

resilience4j.ratelimiter:
  instances:
    apiRateLimit:
      limitForPeriod: 500
      limitRefreshPeriod: 60s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

resilience4j.timelimiter:
  instances:
    apiTimeLimit:
      timeoutDuration: 10s
      cancelRunningFuture: false


