spring:
  application:
    name: trade-vision-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers

logging:
  level:
    root: INFO

