spring:
  application:
    name: trade-vision-backend

  task:
    scheduling:
      pool:
        size: 1

  modulith:
    events:
      completion:
        mode: delete
      jdbc-schema-initialization:
        enabled: true

  datasource:
    # url: jdbc:postgresql://db.wnwrnwiwmlwhlfzocmpo.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

logging:
  level:
    root: INFO

