spring:
  application:
    name: data-processing-service

  datasource:
    url:
      jdbc:
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

  kafka:
    topic: status
    consumer:
      bootstrap-servers: localhost:9092
      group-id: processing
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.data_processing_service.dto

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers

logging:
  level:
    root: INFO
